FROM inventree/inventree:stable


ENV HOME /root
ADD contrib/container/init.sh /home/inventree/init.sh
RUN chmod -R o+w /home/inventree/src/backend/InvenTree && \
     chmod -R o+x /root && \
     chmod -R o+r /root && \
     chmod -R g+r /root && \
     chmod -R g+x /root && \
     chmod g+w /root && \
     chmod -R g+w /home/inventree

USER 1001
